controllers/DeviceController.php
<?php

namespace app\controllers;

use app\models\Place;
use app\models\SensorData;
use Yii;
use app\models\Device;
use app\models\search\DeviceSearch;
use yii\helpers\ArrayHelper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * DeviceController implements the CRUD actions for Device model.
 */
class DeviceController extends BaseController
{

    /**
     * Lists all Device models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new DeviceSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Lists all Device models.
     * @return mixed
     */
    public function actionIndexReadOnly()
    {
        $searchModel = new DeviceSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $gridViewColumns = $searchModel->getColumns();

        return $this->render('index-read-only.php', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'gridViewColumns' => $gridViewColumns
        ]);
    }

    /**
     * Displays a single Device model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Device model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Device();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        $places = Place::find()->all();
        $placeSelect2Data = ArrayHelper::map($places, 'id', 'name');

        return $this->render('create', [
            'model' => $model,
            'placeSelect2Data' => $placeSelect2Data,
        ]);
    }

    /**
     * Updates an existing Device model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        $places = Place::find()->all();
        $placeSelect2Data = ArrayHelper::map($places, 'id', 'name');

        return $this->render('create', [
            'model' => $model,
            'placeSelect2Data' => $placeSelect2Data,
        ]);
    }

    /**
     * Deletes an existing Device model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Device model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Device the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Device::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }
}

controllers/DeviceErrorController.php
<?php

namespace app\controllers;

use Yii;
use app\models\DeviceError;
use app\models\search\DeviceError as DeviceErrorSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * DeviceErrorController implements the CRUD actions for DeviceError model.
 */
class DeviceErrorController extends BaseController
{
    /**
     * Lists all DeviceError models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new DeviceErrorSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Finds the DeviceError model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return DeviceError the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = DeviceError::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

controllers/PlaceController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Place;
use app\models\search\PlaceSearch;
use yii\web\NotFoundHttpException;

/**
 * PlaceController implements the CRUD actions for Place model.
 */
class PlaceController extends BaseController
{
    /**
     * Lists all Place models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new PlaceSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Place model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Place model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Place();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Place model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Place model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Place model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Place the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Place::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

controllers/SensorDataController.php
<?php

namespace app\controllers;

use Yii;
use app\models\SensorData;
use app\models\search\SensorDataSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * SensorDataController implements the CRUD actions for SensorData model.
 */
class SensorDataController extends BaseController
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all SensorData models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new SensorDataSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single SensorData model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new SensorData model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new SensorData();
        $model->load(Yii::$app->request->post());
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing SensorData model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing SensorData model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the SensorData model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return SensorData the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = SensorData::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }
}

views/layouts/_content.php
<div class="content-wrapper">

    <section class="content container-fluid">

        <?= $content; ?>

    </section>

</div>

views/layouts/_header.php
<header class="main-header">
    <a href="/" class="logo">
        <span class="logo-mini"><i class="fa fa-clock-o" aria-hidden="true"></i></span>
        <span class="logo-lg"><b>Sensor</b>Monitor</span>
    </a>
    
    <nav class="navbar navbar-static-top" role="navigation">
        <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>
        <!-- Navbar Right Menu -->
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                <li>
                    <a href="/user-management/auth/logout"><i class="fa fa-sign-out" aria-hidden="true"></i> Kijelentkezés </a>
                </li>
            </ul>
        </div>
    </nav>
</header>

views/layouts/_left_side.php
<?php
use webvimark\modules\UserManagement\components\GhostMenu;
use webvimark\modules\UserManagement\UserManagementModule;
?>

<aside class="main-sidebar">

    <section class="sidebar">
        <?= GhostMenu::widget([
            'encodeLabels' => false,
            'activateParents' => true,
            'options' => [
                    'class' => 'sidebar-menu',
                    'data-widget' => 'tree',
                ],
            'items' => [
                ['label' => '<i class="fa fa-home" aria-hidden="true"></i> Mérőhelyek', 'url' => ['/place/index']],
                ['label' => '<i class="fa fa-microchip" aria-hidden="true"></i> Eszközök', 'url' => ['/device/index']],
                ['label' => '<i class="fa fa-exclamation-triangle " aria-hidden="true"></i> Eszköz hibák', 'url' => ['/device-error/index']],
                ['label' => '<i class="fa fa-rss" aria-hidden="true"></i>Eszközök állapota', 'url' => ['/device/index-read-only']],
                ['label' => '<i class="fa fa-cogs" aria-hidden="true"></i> Sensoradatok', 'url' => ['/sensor-data/index']],
                ['label' => '<i class="fa fa-thermometer-full" aria-hidden="true"></i> Hő és Nyom. mérések', 'url' => ['/measurement/index']],
                ['label' => '<i class="fa fa-thermometer-full" aria-hidden="true"></i>  Hőmérséklet statisztika', 'url' => ['/measurement/meassure-stat']],
                ['label' => '<i class="fa fa-tint" aria-hidden="true"></i>  Nyomás statisztika', 'url' => ['/measurement/pressure-stat']],
                ['label' => '<i class="fa fa-bar-chart" aria-hidden="true"></i> Csoportos statisztika', 'url' => ['/measurement/groups-stat']],
                ['label' => '<i class="fa fa-lightbulb-o" aria-hidden="true"></i> Fény mérések', 'url' => ['/light-measurement/index']],
                ['label' => '<i class="fa fa-lightbulb-o" aria-hidden="true"></i> Fény mérés stat. (PAR)', 'url' => ['/light-measurement/light-stat']],
                ['label' => '<i class="fa fa-lightbulb-o" aria-hidden="true"></i> Fény mérés stat. (DLI) ', 'url' => ['/light-measurement/dli-stat']],
                ['label' => '<i class="fa fa-lightbulb-o" aria-hidden="true"></i> DLI napi statisztika', 'url' => ['/light-measurement/dli-stat-daily']],
                ['label' => '<i class="fa fa-info" aria-hidden="true"></i> Névjegy', 'url' => ['/site/about']],

                ['label' => '<i class="fa fa-wrench" aria-hidden="true"></i> Felhasználókezelés', 'url' => ['/user-management/user/index']],
                ['label' => '<i class="fa fa-wrench" aria-hidden="true"></i> Roles', 'url' => ['/user-management/role/index']],
                ['label' => '<i class="fa fa-wrench" aria-hidden="true"></i> Permissions', 'url' => ['/user-management/permission/index']],
                ['label' => '<i class="fa fa-wrench" aria-hidden="true"></i> Permission groups', 'url' => ['/user-management/auth-item-group/index']],
                ['label' => '<i class="fa fa-wrench" aria-hidden="true"></i> Visit log', 'url' => ['/user-management/user-visit-log/index']],

            ],
        ]);
        ?>
    </section>


</aside>

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use app\assets\AppAsset;

AppAsset::register($this);

?>

<?php $this->beginPage() ?>

<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
    <head>
        <meta charset="<?= Yii::$app->charset ?>">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <?= Html::csrfMetaTags() ?>

        <title><?= Html::encode($this->title) ?></title>

        <?php $this->head(); ?>
    </head>


    <body class="hold-transition skin-blue sidebar-mini">
        <?php $this->beginBody() ?>

        <div class="wrapper">
            <?= $this->render('_header'); ?>
            <?= $this->render('_left_side'); ?>
            <?= $this->render('_content', [
                    'content' => $content
                ]); ?>
        </div>

        <?php $this->endBody() ?>
    </body>
</html>

<?php $this->endPage() ?>